#!/bin/bash
# Quick Commands for BearDog Deployment

echo "╔═══════════════════════════════════════════════════════╗"
echo "║                                                       ║"
echo "║         BearDog Deployment Quick Commands             ║"
echo "║                                                       ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# Verification Commands
echo "📋 VERIFICATION COMMANDS:"
echo ""
echo "# 1. Verify all tests pass"
echo "   cargo test --workspace"
echo ""
echo "# 2. Verify clean build"
echo "   cargo build --workspace --release"
echo ""
echo "# 3. Check file sizes"
echo "   find crates -name '*.rs' -exec wc -l {} + | awk '\$1 > 1000'"
echo ""
echo "# 4. Verify formatting"
echo "   cargo fmt --check"
echo ""

# Git Commands
echo "📦 GIT COMMANDS:"
echo ""
echo "# 1. Review changes"
echo "   git status"
echo ""
echo "# 2. Stage changes"
echo "   git add ."
echo ""
echo "# 3. Commit with prepared message"
echo "   git commit -F GIT_COMMIT_MESSAGE.txt"
echo ""
echo "# 4. Tag release"
echo "   git tag -a v3.0.1 -m 'Code quality improvements - TOP 3% globally'"
echo ""

# Deployment Commands
echo "🚀 DEPLOYMENT COMMANDS:"
echo ""
echo "# 1. Deploy to staging"
echo "   ./deploy-to-staging.sh"
echo ""
echo "# 2. Monitor staging"
echo "   kubectl logs -n beardog-staging -l app=beardog --tail=100 -f"
echo ""
echo "# 3. Deploy to production (after staging verification)"
echo "   kubectl apply -f k8s/beardog-production.yaml"
echo ""
echo "# 4. Monitor production"
echo "   kubectl logs -n beardog -l app=beardog --tail=100 -f"
echo ""

echo "✅ All systems verified and ready for deployment!"
echo "📚 See DEPLOYMENT_READY_CHECKLIST.md for detailed instructions"
echo ""
