#!/bin/bash
# Quick ship commands for v0.9.0-beta
# Run these commands in sequence

echo "🐻🔒 BearDog v0.9.0-beta - Quick Ship Commands"
echo "=============================================="
echo ""
echo "Execute these commands to ship:"
echo ""
echo "# 1. Add all changes"
echo "git add -A"
echo ""
echo "# 2. Commit with prepared message"
echo "git commit -F RELEASE_COMMIT_MESSAGE.txt"
echo ""
echo "# 3. Create annotated tag"
echo "git tag -a v0.9.0-beta -F GIT_TAG_MESSAGE.txt"
echo ""
echo "# 4. Verify tag"
echo "git tag -l -n10 v0.9.0-beta"
echo ""
echo "# 5. Build release"
echo "cargo build --release"
echo ""
echo "# 6. Push to remote (when ready)"
echo "git push origin $(git branch --show-current)"
echo "git push origin v0.9.0-beta"
echo ""
echo "✅ Ready to execute!"
echo ""
echo "To run automatically, use: ./SHIP_BETA_NOW.sh"
