[package]
name = "beardog-production"
description = "BearDog production module"
repository = "https://github.com/ecoPrimals/beardog"
rust-version = "1.93.0"
homepage = "https://beardog.dev"
documentation = "https://docs.rs/beardog"
keywords = [ "production", "enterprise", "beardog", "reliability", "scale",]
categories = [ "development-tools",]
publish = false
readme = "README.md"
license = "AGPL-3.0-or-later"

[package.version]
workspace = true

[package.edition]
workspace = true

[package.authors]
workspace = true

[lints]
workspace = true

[dependencies.beardog-errors]
workspace = true

[dependencies.beardog-security]
workspace = true

[dependencies.beardog-types]
workspace = true

[dependencies.beardog-config]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.chrono]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.toml]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.base64]
workspace = true

[dependencies.blake3]
workspace = true

[dependencies.hex]
workspace = true

[dependencies.parking_lot]
workspace = true

[dependencies.hkdf]
workspace = true

[dependencies.sha2]
workspace = true

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.serial_test]
workspace = true
