// SPDX-License-Identifier: AGPL-3.0-or-later

//! Alert types, severity levels, and the [`AlertHandler`] trait.

use beardog_errors::BearDogError;

/// Implementors of this trait can process various types of system alerts.
pub trait AlertHandler: std::fmt::Debug {
    /// Handle a system alert.
    ///
    /// Processes the given alert and takes appropriate action based on the alert type.
    ///
    /// # Errors
    ///
    /// Returns an error if alert handling fails.
    fn handle_alert(&self, alert: SystemAlert) -> Result<(), BearDogError>;
}

/// System alert notification containing details about system events.
///
/// Represents alerts generated by the monitoring system when thresholds
/// are exceeded or components experience issues.
#[derive(Debug, Clone)]
pub struct SystemAlert {
    /// Type of alert being raised.
    pub alert_type: AlertType,
    /// Human-readable description of the alert.
    pub message: String,
    /// Severity level of the alert.
    pub severity: AlertSeverity,
    /// Timestamp when the alert was generated.
    pub timestamp: chrono::DateTime<chrono::Utc>,
    /// Component that triggered the alert (if applicable).
    pub component: Option<String>,
    /// Metric value that triggered the alert (if applicable).
    pub metric_value: Option<f64>,
}

/// Types of system alerts that can be generated.
///
/// Categorizes different kinds of system events that warrant attention,
/// from resource utilization issues to component failures.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertType {
    /// CPU usage has exceeded the configured threshold.
    HighCpuUsage,
    /// Memory usage has exceeded the configured threshold.
    HighMemoryUsage,
    /// Disk usage has exceeded the configured threshold.
    HighDiskUsage,
    /// A system component has become unavailable.
    ComponentDown,
    /// Error rate has exceeded acceptable levels.
    HighErrorRate,
    /// Response times are slower than expected.
    SlowResponse,
}

/// Indicates the urgency and impact level of system alerts,
/// helping prioritize response actions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertSeverity {
    /// Informational message, no immediate action required.
    Info,
    /// Warning condition that should be monitored.
    Warning,
    /// Critical issue requiring immediate attention.
    Critical,
    /// Emergency situation requiring urgent response.
    Emergency,
}
