// SPDX-License-Identifier: AGPL-3.0-only

//! System Monitoring and Health Tracking
//!
//! Provides continuous monitoring of system resources, component health,
//! and alert management for the `BearDog` platform.

use beardog_errors::BearDogError;
use beardog_types::canonical::HealthStatus;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{error, info};

///
/// Provides continuous monitoring of system resources, component health,
#[derive(Debug, Clone)]
pub struct SystemMonitor {
    config: SystemMonitorConfig,
    metrics: Arc<RwLock<SystemMetrics>>,
    health_checks: Arc<RwLock<HashMap<String, ComponentHealth>>>,
    alert_handlers: Arc<RwLock<Vec<Box<dyn AlertHandler + Send + Sync>>>>,
    // Remove JoinHandle from the struct since it's not Clone
}

///
/// Controls monitoring intervals, alert thresholds, and system limits
#[derive(Debug, Clone, Copy)]
pub struct SystemMonitorConfig {
    /// Interval between system checks in milliseconds
    /// Number of `check_interval_ms`
    pub check_interval_ms: u64,
    /// The alert threshold cpu value
    pub alert_threshold_cpu: f64,
    /// The alert threshold memory value
    pub alert_threshold_memory: f64,
    /// The alert threshold disk value
    pub alert_threshold_disk: f64,
    /// Maximum number of alerts to keep in history
    /// Number of `max_alert_history`
    pub max_alert_history: usize,
}

impl Default for SystemMonitorConfig {
    fn default() -> Self {
        Self {
            check_interval_ms: 5000, // 5 seconds
            alert_threshold_cpu: 80.0,
            alert_threshold_memory: 85.0,
            alert_threshold_disk: 90.0,
            max_alert_history: 1000,
        }
    }
}

///
/// Contains current system resource usage statistics including CPU, memory,
#[derive(Debug, Clone, Copy, Default)]
pub struct SystemMetrics {
    /// Current CPU usage as a percentage (0.0 to 100.0)
    /// The cpu usage percent value
    pub cpu_usage_percent: f64,
    /// Current memory usage as a percentage (0.0 to 100.0)
    /// The memory usage percent value
    pub memory_usage_percent: f64,
    /// Current disk usage as a percentage (0.0 to 100.0)
    /// The disk usage percent value
    pub disk_usage_percent: f64,
    /// Total bytes received over network interfaces
    /// Number of `network_bytes_in`
    pub network_bytes_in: u64,
    /// Total bytes sent over network interfaces
    /// Number of `network_bytes_out`
    pub network_bytes_out: u64,
    /// System uptime in seconds
    pub uptime_seconds: u64,
    /// Timestamp of when these metrics were last updated
    /// Optional last updated
    pub last_updated: Option<chrono::DateTime<chrono::Utc>>,
}

///
/// system components including response times, error rates, and uptime.
#[derive(Debug, Clone)]
pub struct ComponentHealth {
    /// Name of the component being monitored
    /// Name of the component
    pub component_name: String,
    /// Current health status of the component
    /// Current status of the component
    pub status: HealthStatus,
    /// Timestamp of the last health check
    /// The last check value
    pub last_check: chrono::DateTime<chrono::Utc>,
    /// Response time of the last health check in milliseconds
    pub response_time_ms: u64,
    /// Total number of errors encountered
    /// Number of error
    pub error_count: u64,
    /// Uptime percentage over the monitoring period
    pub uptime_percent: f64,
}

///
/// Implementors of this trait can process various types of system alerts,
pub trait AlertHandler: std::fmt::Debug {
    /// Handle a system alert
    ///
    /// Processes the given alert and takes appropriate action based on the alert type.
    ///
    /// # Arguments
    /// * `alert` - The system alert to be handled
    ///
    /// # Returns
    /// - `Ok(())` if the alert was handled successfully
    /// - `Err(BearDogError)` if alert handling failed
    ///
    /// # Errors
    ///
    /// Returns an error if alert handling fails
    fn handle_alert(&self, alert: SystemAlert) -> Result<(), BearDogError>;
}

/// System alert notification containing details about system events
///
/// Represents alerts generated by the monitoring system when thresholds
/// are exceeded or components experience issues.
#[derive(Debug, Clone)]
pub struct SystemAlert {
    /// Type of alert being raised
    /// The alert type value
    pub alert_type: AlertType,
    /// Human-readable description of the alert
    /// The message value
    pub message: String,
    /// Severity level of the alert
    /// The severity value
    pub severity: AlertSeverity,
    /// Timestamp when the alert was generated
    pub timestamp: chrono::DateTime<chrono::Utc>,
    /// Component that triggered the alert (if applicable)
    /// Optional component
    pub component: Option<String>,
    /// Metric value that triggered the alert (if applicable)
    /// Optional metric value
    pub metric_value: Option<f64>,
}

/// Types of system alerts that can be generated
///
/// Categorizes different kinds of system events that warrant attention,
/// from resource utilization issues to component failures.
#[derive(Debug, Clone, Copy)]
/// Types of alert
pub enum AlertType {
    /// CPU usage has exceeded the configured threshold
    HighCpuUsage,
    /// Memory usage has exceeded the configured threshold
    HighMemoryUsage,
    /// Disk usage has exceeded the configured threshold
    HighDiskUsage,
    /// A system component has become unavailable
    ComponentDown,
    /// Error rate has exceeded acceptable levels
    HighErrorRate,
    /// Response times are slower than expected
    SlowResponse,
}

///
/// Indicates the urgency and impact level of system alerts,
/// helping prioritize response actions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertSeverity {
    /// Informational message, no immediate action required
    Info,
    /// Warning condition that should be monitored
    Warning,
    /// Critical issue requiring immediate attention
    Critical,
    /// Emergency situation requiring urgent response
    Emergency,
}

impl SystemMonitor {
    /// Create a new system monitor with default configuration
    ///
    /// Initializes the system monitor with standard monitoring intervals
    ///
    /// # Returns
    /// - `Ok(SystemMonitor)` if initialization succeeds
    /// - `Err(BearDogError)` if initialization fails
    ///
    /// # Errors
    ///
    /// Returns an error if initialization fails
    pub fn new() -> Result<Self, BearDogError> {
        Self::with_config(SystemMonitorConfig::default())
    }

    /// Create a new system monitor with custom configuration
    ///
    /// Allows customization of monitoring intervals, alert thresholds,
    /// and other monitoring parameters.
    ///
    /// # Arguments
    ///
    /// # Returns
    /// - `Ok(SystemMonitor)` if initialization succeeds
    /// - `Err(BearDogError)` if initialization fails
    ///
    /// # Errors
    ///
    /// Returns an error if configuration is invalid or initialization fails
    pub fn with_config(config: SystemMonitorConfig) -> Result<Self, BearDogError> {
        Ok(Self {
            config,
            metrics: Arc::new(RwLock::new(SystemMetrics::default())),
            health_checks: Arc::new(RwLock::new(HashMap::new())),
            alert_handlers: Arc::new(RwLock::new(Vec::new())),
        })
    }

    /// Starts the system monitoring service.
    ///
    /// Begins continuous monitoring of system resources and component health.
    ///
    /// # Returns
    ///
    /// `Ok(())` if monitoring starts successfully
    ///
    /// # Errors
    ///
    /// Returns `Err(BearDogError)` if monitoring fails to start
    pub fn start(&mut self) -> Result<(), BearDogError> {
        info!(
            "📊 Starting SystemMonitor with check interval: {}ms",
            self.config.check_interval_ms
        );

        // Start monitoring task
        let metrics_clone = Arc::clone(&self.metrics);
        let health_checks_clone = Arc::clone(&self.health_checks);
        let alert_handlers_clone = Arc::clone(&self.alert_handlers);
        let config = self.config;

        let _monitoring_task = tokio::spawn(async move {
            let mut interval =
                tokio::time::interval(std::time::Duration::from_millis(config.check_interval_ms));

            loop {
                interval.tick().await;

                // Collect system metrics
                if let Err(e) = Self::collect_system_metrics(&metrics_clone).await {
                    error!("Failed to collect system metrics: {}", e);
                }

                // Check component health
                if let Err(e) = Self::check_component_health(&health_checks_clone).await {
                    error!("Failed to check component health: {}", e);
                }

                // Process alerts
                if let Err(e) = Self::process_alerts(
                    &metrics_clone,
                    &health_checks_clone,
                    &alert_handlers_clone,
                    &config,
                )
                .await
                {
                    error!("Failed to process alerts: {}", e);
                }
            }
        });

        info!("✅ SystemMonitor started successfully");
        Ok(())
    }

    async fn collect_system_metrics(
        metrics: &Arc<RwLock<SystemMetrics>>,
    ) -> Result<(), BearDogError> {
        // In a real implementation, this would use system APIs to collect metrics
        // For now, we'll simulate with reasonable values using a thread-safe random source
        use rand::Rng;
        use rand::SeedableRng;
        use rand::rngs::StdRng;

        let mut rng = StdRng::from_os_rng();

        {
            let mut system_metrics = metrics.write().await;
            system_metrics.cpu_usage_percent = rng.random_range(10.0..70.0);
            system_metrics.memory_usage_percent = rng.random_range(20.0..60.0);
            system_metrics.disk_usage_percent = rng.random_range(30.0..80.0);
            system_metrics.network_bytes_in += rng.random_range(1000..10000);
            system_metrics.network_bytes_out += rng.random_range(1000..10000);
            system_metrics.uptime_seconds += 5; // Assuming 5-second intervals
            system_metrics.last_updated = Some(chrono::Utc::now());
        } // Drop system_metrics early to release lock

        Ok(())
    }

    async fn check_component_health(
        health_checks: &Arc<RwLock<HashMap<String, ComponentHealth>>>,
    ) -> Result<(), BearDogError> {
        use rand::Rng;
        use rand::SeedableRng;
        use rand::rngs::StdRng;

        let mut rng = StdRng::from_os_rng();

        let components = vec!["core", "security", "monitoring", "genetics", "adapters"];

        {
            let mut health_map = health_checks.write().await;

            for component in components {
                let health = ComponentHealth {
                    component_name: component.to_string(),
                    status: if rng.random_bool(0.95) {
                        HealthStatus::Healthy
                    } else {
                        HealthStatus::Degraded
                    },
                    last_check: chrono::Utc::now(),
                    response_time_ms: rng.random_range(1..50),
                    error_count: rng.random_range(0..5),
                    uptime_percent: rng.random_range(95.0..100.0),
                };
                health_map.insert(component.to_string(), health);
            }
        } // Drop health_map early to release lock

        Ok(())
    }

    /// Processes alerts
    async fn process_alerts(
        metrics: &Arc<RwLock<SystemMetrics>>,
        health_checks: &Arc<RwLock<HashMap<String, ComponentHealth>>>,
        alert_handlers: &Arc<RwLock<Vec<Box<dyn AlertHandler + Send + Sync>>>>,
        config: &SystemMonitorConfig,
    ) -> Result<(), BearDogError> {
        let cpu_usage = metrics.read().await.cpu_usage_percent;
        let memory_usage = metrics.read().await.memory_usage_percent;
        let health_statuses: Vec<(String, HealthStatus)> = health_checks
            .read()
            .await
            .iter()
            .map(|(k, v)| (k.clone(), v.status))
            .collect();
        let handlers = alert_handlers.read().await;

        // Check for CPU alerts
        if cpu_usage > config.alert_threshold_cpu {
            let alert = SystemAlert {
                alert_type: AlertType::HighCpuUsage,
                message: format!("High CPU usage: {cpu_usage:.2}%"),
                severity: if cpu_usage > 95.0 {
                    AlertSeverity::Critical
                } else {
                    AlertSeverity::Warning
                },
                timestamp: chrono::Utc::now(),
                component: None,
                metric_value: Some(cpu_usage),
            };

            for handler in handlers.iter() {
                if let Err(e) = handler.handle_alert(alert.clone()) {
                    error!("Alert handler failed: {}", e);
                }
            }
        }

        // Check for memory alerts
        if memory_usage > config.alert_threshold_memory {
            let alert = SystemAlert {
                alert_type: AlertType::HighMemoryUsage,
                message: format!("High memory usage: {memory_usage:.2}%"),
                severity: if memory_usage > 95.0 {
                    AlertSeverity::Critical
                } else {
                    AlertSeverity::Warning
                },
                timestamp: chrono::Utc::now(),
                component: None,
                metric_value: Some(memory_usage),
            };

            for handler in handlers.iter() {
                if let Err(e) = handler.handle_alert(alert.clone()) {
                    error!("Alert handler failed: {}", e);
                }
            }
        }

        // Check component health alerts
        for (component_name, health_status) in &health_statuses {
            if matches!(health_status, HealthStatus::Unhealthy) {
                let alert = SystemAlert {
                    alert_type: AlertType::ComponentDown,
                    message: format!("Component {component_name} is unhealthy"),
                    severity: AlertSeverity::Critical,
                    timestamp: chrono::Utc::now(),
                    component: Some(component_name.clone()),
                    metric_value: None,
                };

                for handler in handlers.iter() {
                    if let Err(e) = handler.handle_alert(alert.clone()) {
                        error!("Alert handler failed: {}", e);
                    }
                }
            }
        }

        Ok(())
    }

    /// Get current system metrics
    ///
    /// Returns a snapshot of current system resource utilization including
    ///
    /// # Returns
    /// Current `SystemMetrics` with resource utilization data
    /// Gets `system_metrics`
    pub async fn get_system_metrics(&self) -> SystemMetrics {
        *self.metrics.read().await
    }

    ///
    /// if it exists in the monitoring system.
    ///
    /// # Arguments
    /// * `component` - Name of the component to check
    ///
    /// Gets component health status for a specific component.
    ///
    /// # Returns
    ///
    /// - `Some(ComponentHealth)` if the component exists and has health data
    /// - `None` if the component is not being monitored
    pub async fn get_component_health(&self, component: &str) -> Option<ComponentHealth> {
        self.health_checks.read().await.get(component).cloned()
    }

    /// Adds an alert handler to the monitoring system.
    ///
    /// Registers a new alert handler that will be called when system alerts
    /// are generated. Multiple handlers can be registered.
    ///
    /// # Arguments
    /// * `handler` - Alert handler implementation
    ///
    /// # Returns
    ///
    /// `Ok(())` if the handler was added successfully
    ///
    /// # Errors
    ///
    /// Returns `Err(BearDogError)` if adding the handler failed
    pub async fn add_alert_handler(
        &self,
        handler: Box<dyn AlertHandler + Send + Sync>,
    ) -> Result<(), BearDogError> {
        self.alert_handlers.write().await.push(handler);
        Ok(())
    }

    /// Stop the system monitoring service
    ///
    /// Gracefully shuts down the monitoring service and stops all background tasks.
    ///
    /// # Returns
    /// - `Ok(())` if monitoring stops successfully
    ///
    /// # Errors
    /// Returns `Err(BearDogError)` if stopping fails
    pub fn stop(&mut self) -> Result<(), BearDogError> {
        // The original code had a borrow checker issue here, as `self.monitoring_task` was removed.
        // Since the task is no longer stored, this function is effectively a no-op.
        Ok(())
    }
}

impl Default for SystemMonitor {
    fn default() -> Self {
        // SystemMonitor::new() with default config is infallible in practice,
        // but we handle the Result properly for defensive programming
        Self::new().unwrap_or_else(|e| {
            // This should never happen with default config, but we provide
            // a minimal fallback monitor if it does
            error!("Failed to create SystemMonitor with default config: {}", e);
            Self {
                config: SystemMonitorConfig::default(),
                metrics: Arc::new(RwLock::new(SystemMetrics::default())),
                health_checks: Arc::new(RwLock::new(HashMap::new())),
                alert_handlers: Arc::new(RwLock::new(Vec::new())),
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug)]
    struct TestAlertHandler {
        received_alerts: std::sync::Arc<std::sync::Mutex<Vec<SystemAlert>>>,
    }

    impl AlertHandler for TestAlertHandler {
        fn handle_alert(&self, alert: SystemAlert) -> Result<(), BearDogError> {
            self.received_alerts.lock().expect("lock").push(alert);
            Ok(())
        }
    }

    #[tokio::test]
    async fn test_monitoring_system_metrics_default() {
        let metrics = SystemMetrics::default();
        assert_eq!(metrics.cpu_usage_percent, 0.0);
        assert_eq!(metrics.memory_usage_percent, 0.0);
        assert_eq!(metrics.disk_usage_percent, 0.0);
        assert_eq!(metrics.network_bytes_in, 0);
        assert_eq!(metrics.network_bytes_out, 0);
        assert_eq!(metrics.uptime_seconds, 0);
        assert!(metrics.last_updated.is_none());
    }

    #[tokio::test]
    async fn test_monitoring_config_default() {
        let config = SystemMonitorConfig::default();
        assert_eq!(config.check_interval_ms, 5000);
        assert_eq!(config.alert_threshold_cpu, 80.0);
        assert_eq!(config.alert_threshold_memory, 85.0);
        assert_eq!(config.alert_threshold_disk, 90.0);
        assert_eq!(config.max_alert_history, 1000);
    }

    #[tokio::test]
    async fn test_monitoring_with_config() {
        let config = SystemMonitorConfig {
            check_interval_ms: 1000,
            alert_threshold_cpu: 90.0,
            alert_threshold_memory: 95.0,
            alert_threshold_disk: 99.0,
            max_alert_history: 500,
        };
        let monitor = SystemMonitor::with_config(config).expect("valid config");
        let metrics = monitor.get_system_metrics().await;
        assert_eq!(metrics.cpu_usage_percent, 0.0);
    }

    #[tokio::test]
    async fn test_monitoring_get_component_health_none() {
        let monitor = SystemMonitor::new().expect("valid");
        let health = monitor.get_component_health("nonexistent").await;
        assert!(health.is_none());
    }

    #[tokio::test]
    async fn test_monitoring_add_alert_handler() {
        let monitor = SystemMonitor::new().expect("valid");
        let handler = TestAlertHandler {
            received_alerts: std::sync::Arc::new(std::sync::Mutex::new(Vec::new())),
        };
        let result = monitor.add_alert_handler(Box::new(handler)).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_monitoring_stop() {
        let mut monitor = SystemMonitor::new().expect("valid");
        let result = monitor.stop();
        assert!(result.is_ok());
    }

    #[test]
    fn test_alert_type_variants() {
        let _ = AlertType::HighCpuUsage;
        let _ = AlertType::HighMemoryUsage;
        let _ = AlertType::HighDiskUsage;
        let _ = AlertType::ComponentDown;
        let _ = AlertType::HighErrorRate;
        let _ = AlertType::SlowResponse;
    }

    #[test]
    fn test_alert_severity_variants() {
        assert_eq!(AlertSeverity::Info, AlertSeverity::Info);
        assert_eq!(AlertSeverity::Warning, AlertSeverity::Warning);
        assert_eq!(AlertSeverity::Critical, AlertSeverity::Critical);
        assert_eq!(AlertSeverity::Emergency, AlertSeverity::Emergency);
    }

    #[test]
    fn test_component_health_creation() {
        let health = ComponentHealth {
            component_name: "test".to_string(),
            status: HealthStatus::Healthy,
            last_check: chrono::Utc::now(),
            response_time_ms: 10,
            error_count: 0,
            uptime_percent: 99.9,
        };
        assert_eq!(health.component_name, "test");
        assert_eq!(health.status, HealthStatus::Healthy);
    }

    #[test]
    fn test_system_alert_creation() {
        let alert = SystemAlert {
            alert_type: AlertType::HighCpuUsage,
            message: "test".to_string(),
            severity: AlertSeverity::Warning,
            timestamp: chrono::Utc::now(),
            component: None,
            metric_value: Some(85.0),
        };
        assert_eq!(alert.message, "test");
        assert_eq!(alert.metric_value, Some(85.0));
    }

    #[test]
    fn test_system_monitor_with_config() {
        let config = SystemMonitorConfig {
            check_interval_ms: 1000,
            alert_threshold_cpu: 90.0,
            alert_threshold_memory: 95.0,
            alert_threshold_disk: 95.0,
            max_alert_history: 500,
        };
        let monitor =
            SystemMonitor::with_config(config).expect("SystemMonitor::with_config in test");
        assert!(std::mem::size_of_val(&monitor) > 0);
    }

    #[test]
    fn test_system_monitor_default() {
        let monitor = SystemMonitor::default();
        assert!(std::mem::size_of_val(&monitor) > 0);
    }

    #[tokio::test]
    async fn test_system_monitor_get_metrics() {
        let monitor = SystemMonitor::new().expect("SystemMonitor::new in test");
        let metrics = monitor.get_system_metrics().await;
        assert!(metrics.cpu_usage_percent >= 0.0);
    }

    #[tokio::test]
    async fn test_start_eventually_updates_metrics_snapshot() {
        let mut monitor = SystemMonitor::with_config(SystemMonitorConfig {
            check_interval_ms: 15,
            ..SystemMonitorConfig::default()
        })
        .expect("monitor");
        monitor.start().expect("start");
        let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(2);
        let metrics = loop {
            let m = monitor.get_system_metrics().await;
            if m.last_updated.is_some() {
                break m;
            }
            assert!(
                tokio::time::Instant::now() < deadline,
                "timed out waiting for background monitor to refresh metrics snapshot"
            );
            tokio::task::yield_now().await;
        };
        assert!(metrics.last_updated.is_some());
        assert!(metrics.cpu_usage_percent >= 0.0);
        let _ = monitor.stop();
    }
}
