[package]
name = "beardog-auth"
description = "BearDog auth module"
repository = "https://github.com/ecoPrimals/beardog"
rust-version = "1.93.0"
homepage = "https://beardog.dev"
documentation = "https://docs.rs/beardog"
keywords = [ "auth", "authentication", "authorization", "beardog", "security",]
categories = [ "authentication", "security", "development-tools",]
license = "AGPL-3.0-or-later"

[package.version]
workspace = true

[package.edition]
workspace = true

[package.authors]
workspace = true

[lints]
workspace = true

[dependencies.beardog-errors]
workspace = true

[dependencies.beardog-types]
workspace = true

[dependencies.beardog-traits]
workspace = true

[dependencies.beardog-security]
workspace = true

[dependencies.beardog-capabilities]
workspace = true

[dependencies.tokio]
workspace = true
features = ["rt", "macros"]

[dependencies.serde]
workspace = true

[dependencies.chrono]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.argon2]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.parking_lot]
workspace = true

[dependencies.base64]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.ed25519-dalek]
workspace = true

[dependencies.sha3]
workspace = true

[dependencies.blake3]
workspace = true
