// SPDX-License-Identifier: AGPL-3.0-only

// Entropy Hierarchy Types
//
// This module defines the core types for the entropy hierarchy system,
// supporting human-centric entropy classification and management.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
// Note: zeroize could be added for secure memory clearing in production
use std::collections::HashMap;

/// Classification of entropy sources based on human involvement and quality
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum EntropyClass {
    /// Entropy directly generated by human lived experience
    HumanLivedExperience {
        /// Human-generated entropy quality score (0.0-1.0)
        quality_score: f64,
        /// When the entropy was captured
        capture_timestamp: DateTime<Utc>,
        /// Biometric commitment binding this entropy to a person without storing raw biometrics.
        biometric_signature: BiometricHash,
        /// Proof of ownership
        ownership_proof: OwnershipProof,
    },
    /// Machine entropy supervised by humans
    HumanSupervisedMachine {
        /// Quality score with human supervision (0.0-1.0)
        quality_score: f64,
        /// Machine source details
        machine_source: MachineEntropySource,
        /// Human validator identity
        human_validator: HumanIdentity,
        /// When validation occurred
        validation_timestamp: DateTime<Utc>,
    },
    /// Store-bought machine entropy (lowest quality)
    StoreBoughtMachine {
        /// Estimated quality of the machine-only entropy (0.0–1.0).
        quality_score: f64,
        /// Machine source type
        source_type: MachineEntropySource,
        /// When entropy was generated
        generation_timestamp: DateTime<Utc>,
        /// Reproducibility index (higher = more predictable)
        reproducibility_index: f64,
    },
}

impl PartialOrd for EntropyClass {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        let self_precedence = match self {
            Self::HumanLivedExperience { .. } => 3,
            Self::HumanSupervisedMachine { .. } => 2,
            Self::StoreBoughtMachine { .. } => 1,
        };
        let other_precedence = match other {
            Self::HumanLivedExperience { .. } => 3,
            Self::HumanSupervisedMachine { .. } => 2,
            Self::StoreBoughtMachine { .. } => 1,
        };
        self_precedence.partial_cmp(&other_precedence)
    }
}

/// One-way representation of human biometric material plus an ownership binding.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BiometricHash {
    /// Hash of biometric data
    /// Collection of hash
    pub hash: Vec<u8>,
    /// Ownership proof data
    /// Collection of ownership proof
    pub ownership_proof: Vec<u8>,
}

impl BiometricHash {
    /// Create new biometric hash
    /// Creates a new instance
    #[must_use]
    pub const fn new(hash: Vec<u8>, ownership_proof: Vec<u8>) -> Self {
        Self {
            hash,
            ownership_proof,
        }
    }
}

/// Evidence that the human operator consents to use of their entropy class in derivation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OwnershipProof {
    /// Proof data
    /// Collection of proof data
    pub proof_data: Vec<u8>,
    /// Digital signature
    /// Collection of signature
    pub signature: Vec<u8>,
    /// Timestamp of proof creation
    pub timestamp: DateTime<Utc>,
}

impl OwnershipProof {
    /// Create new ownership proof
    /// Creates a new instance
    #[must_use]
    pub fn new(proof_data: Vec<u8>, signature: Vec<u8>) -> Self {
        Self {
            proof_data,
            signature,
            timestamp: Utc::now(),
        }
    }
}

/// Captured human entropy with modality metadata and collection time.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct HumanEntropySource {
    /// Type of human entropy source
    /// The source type value
    pub source_type: HumanEntropyType,
    /// Raw entropy data
    /// Collection of entropy data
    pub entropy_data: Vec<u8>,
    /// Collection timestamp
    /// The collected at value
    pub collected_at: DateTime<Utc>,
}

/// Modalities through which humans contribute unpredictable input to the hierarchy.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum HumanEntropyType {
    /// Biometric data (fingerprint, voice, etc.)
    Biometric {
        /// Logical modality name (e.g. fingerprint, voice) for policy routing.
        biometric_type: String,
        /// Normalized quality estimate for this sample.
        quality_score: f64,
    },
    /// Behavioral patterns
    Behavioral {
        /// Class of behavior captured (e.g. typing rhythm).
        pattern_type: String,
        /// How unpredictable the pattern is relative to population baselines.
        complexity_score: f64,
    },
    /// Creative expression
    Creative {
        /// Kind of creative act (drawing, composition) contributing entropy.
        expression_type: String,
        /// Uniqueness score for the creative output.
        uniqueness_score: f64,
    },
}

/// Machine-origin randomness with algorithm and seed-source transparency for auditing.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MachineEntropySource {
    /// Type of machine source
    /// The source type value
    pub source_type: MachineSourceType,
    /// Algorithm used
    /// The algorithm value
    pub algorithm: String,
    /// Source of randomness
    /// The seed source value
    pub seed_source: String,
    /// Quality metrics
    /// Mapping of quality metrics
    pub quality_metrics: HashMap<String, f64>,
}

/// Physical or logical RNG implementation feeding supervised or store-bought entropy.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum MachineSourceType {
    /// Cryptographically secure pseudo-random number generator
    CSPRNG {
        /// Named algorithm (e.g. `ChaCha20`).
        algorithm: String,
        /// Where seed material originates (hardware, OS, etc.).
        seed_source: String,
    },
    /// Hardware random number generator
    HRNG {
        /// Device or API identifier (e.g. TPM 2.0).
        device_type: String,
        /// Observed or rated bits of entropy per sample.
        entropy_rate: f64,
    },
    /// True random number generator
    TRNG {
        /// Physical noise source category (quantum, thermal, …).
        source_type: String,
        /// Battery tests passed by this source (NIST, diehard, …).
        randomness_tests: Vec<String>,
    },
}

/// Human validator referenced when machine entropy is supervised or attested.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HumanIdentity {
    /// Unique identity identifier
    pub identity_id: String,
    /// Hash of identity data
    pub identity_hash: Vec<u8>,
    /// Verification level achieved
    /// The verification level value
    pub verification_level: VerificationLevel,
    /// When identity was verified
    /// The verified at value
    pub verified_at: DateTime<Utc>,
}

/// How strongly a human identity was proven before it may vouch for entropy.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum VerificationLevel {
    /// Basic verification
    Basic,
    /// Enhanced verification with multiple factors
    Enhanced,
    /// Maximum verification with biometrics
    Maximum,
}

/// Describes how multiple entropy buffers are fused before key derivation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FusionAlgorithm {
    /// Algorithm type identifier
    /// The algorithm type value
    pub algorithm_type: String,
    /// Algorithm parameters
    /// Mapping of parameters
    pub parameters: HashMap<String, f64>,
    /// Mixing strategy
    /// The mixing strategy value
    pub mixing_strategy: MixingStrategy,
}

/// Concrete mixing primitive applied inside a [`FusionAlgorithm`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MixingStrategy {
    /// Simple XOR mixing
    XorMix,
    /// Hash-based mixing
    HashMix {
        /// Digest or XOF algorithm identifier.
        hash_algorithm: String,
    },
    /// Cryptographic mixing
    CryptoMix {
        /// AEAD or KDF-capable cipher suite name.
        cipher: String,
    },
}

/// Classified entropy buffer with lifecycle metadata—unit of storage in the hierarchy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntropySeed {
    /// Unique seed identifier
    pub seed_id: Uuid,
    /// Entropy classification
    /// The entropy class value
    pub entropy_class: EntropyClass,
    /// Raw entropy data
    /// Collection of entropy data
    pub entropy_data: Vec<u8>,
    /// Seed metadata
    /// The metadata value
    pub metadata: SeedMetadata,
}

/// Creation time, optional expiry, and usage accounting for an [`EntropySeed`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeedMetadata {
    /// Creation timestamp
    /// The created at value
    pub created_at: DateTime<Utc>,
    /// Expiry timestamp (if any)
    /// Optional expires at
    pub expires_at: Option<DateTime<Utc>>,
    /// Usage count
    /// Number of usage
    pub usage_count: u64,
    /// Maximum allowed usage
    /// Optional max usage
    pub max_usage: Option<u64>,
}

/// Global thresholds for accepting human vs machine entropy and mandatory proofs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntropyHierarchyConfig {
    /// The min human quality value
    pub min_human_quality: f64,
    /// The min machine quality value
    pub min_machine_quality: f64,
    /// Number of `max_entropy_age_hours`
    pub max_entropy_age_hours: u64,
    /// Enable biometric verification
    /// Whether `require_biometric_verification` is enabled
    pub require_biometric_verification: bool,
    /// Enable ownership proofs
    /// Whether `require_ownership_proof` is enabled
    pub require_ownership_proof: bool,
}

impl Default for EntropyHierarchyConfig {
    fn default() -> Self {
        Self {
            min_human_quality: 0.8,
            min_machine_quality: 0.6,
            max_entropy_age_hours: 24,
            require_biometric_verification: true,
            require_ownership_proof: true,
        }
    }
}
