[package]
name = "beardog-threat"
description = "BearDog threat module"
repository = "https://github.com/eastgate-software/beardog"
rust-version = "1.85.0"
homepage = "https://beardog.dev"
documentation = "https://docs.rs/beardog"
keywords = [ "threat", "detection", "analysis", "security", "beardog",]
categories = [ "security", "development-tools", "analysis",]
readme = "README.md"

[package.version]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.authors]
workspace = true

[lints]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.beardog-errors]
path = "../beardog-errors"

[dependencies.beardog-types]
path = "../beardog-types"

[dependencies.chrono]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.uuid]
workspace = true
