#!/bin/bash
# Migration script for beardog-adapters configuration consolidation
# Generated by BearDog Configuration Consolidation Migrator

set -e

CRATE_DIR="crates/beardog-adapters"

echo "Starting configuration migration for beardog-adapters..."

echo "Migrating configurations in crates/beardog-adapters/src/adapters/universal/mod.rs..."

# Add import: use beardog_types::config::CanonicalAdapterConfig;

# Replace UniversalAdapterConfig with canonical type reference
sed -i 's/pub struct UniversalAdapterConfig/// MIGRATED: UniversalAdapterConfig -> CanonicalAdapterConfig/g' "crates/beardog-adapters/src/adapters/universal/mod.rs"

echo "Migrating configurations in crates/beardog-adapters/src/adapters/universal/providers.rs..."

# Add import: use beardog_types::config::UnifiedMonitoringConfig;

# Replace PrometheusConfig with canonical type reference
sed -i 's/pub struct PrometheusConfig/// MIGRATED: PrometheusConfig -> UnifiedMonitoringConfig/g' "crates/beardog-adapters/src/adapters/universal/providers.rs"

echo "Migrating configurations in crates/beardog-adapters/src/adapters/universal/universal_adapter.rs..."

# Add import: use beardog_types::config::UnifiedSecurityConfig;
# Add import: use beardog_types::config::CanonicalAdapterConfig;

# Replace UniversalAdapterConfig with canonical type reference
sed -i 's/pub struct UniversalAdapterConfig/// MIGRATED: UniversalAdapterConfig -> CanonicalAdapterConfig/g' "crates/beardog-adapters/src/adapters/universal/universal_adapter.rs"
# Replace AuthConfig with canonical type reference
sed -i 's/pub struct AuthConfig/// MIGRATED: AuthConfig -> UnifiedSecurityConfig/g' "crates/beardog-adapters/src/adapters/universal/universal_adapter.rs"

echo "Migrating configurations in crates/beardog-adapters/src/adapters/universal/songbird_handoff/types.rs..."

# Add import: use beardog_types::config::UnifiedSecurityConfig;
# Add import: use beardog_types::config::UnifiedMonitoringConfig;
# Add import: use beardog_types::config::UnifiedNetworkConfig;

# Replace SecurityConfig with canonical type reference
sed -i 's/pub struct SecurityConfig/// MIGRATED: SecurityConfig -> UnifiedSecurityConfig/g' "crates/beardog-adapters/src/adapters/universal/songbird_handoff/types.rs"
# Replace HealthCheckConfig with canonical type reference
sed -i 's/pub struct HealthCheckConfig/// MIGRATED: HealthCheckConfig -> UnifiedMonitoringConfig/g' "crates/beardog-adapters/src/adapters/universal/songbird_handoff/types.rs"
# Replace LoadBalancerConfig with canonical type reference
sed -i 's/pub struct LoadBalancerConfig/// MIGRATED: LoadBalancerConfig -> UnifiedNetworkConfig/g' "crates/beardog-adapters/src/adapters/universal/songbird_handoff/types.rs"
# Replace CircuitBreakerConfig with canonical type reference
sed -i 's/pub struct CircuitBreakerConfig/// MIGRATED: CircuitBreakerConfig -> UnifiedNetworkConfig/g' "crates/beardog-adapters/src/adapters/universal/songbird_handoff/types.rs"
# Replace HealthMonitorConfig with canonical type reference
sed -i 's/pub struct HealthMonitorConfig/// MIGRATED: HealthMonitorConfig -> UnifiedMonitoringConfig/g' "crates/beardog-adapters/src/adapters/universal/songbird_handoff/types.rs"

echo "Migrating configurations in crates/beardog-adapters/src/adapters/universal/songbird_handoff/health.rs..."

# Add import: use beardog_types::config::UnifiedMonitoringConfig;

# Replace HealthMonitorConfig with canonical type reference
sed -i 's/pub struct HealthMonitorConfig/// MIGRATED: HealthMonitorConfig -> UnifiedMonitoringConfig/g' "crates/beardog-adapters/src/adapters/universal/songbird_handoff/health.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/extensible_adapter.rs..."

# Add import: use beardog_types::config::CanonicalAdapterConfig;

# Replace ExtensibleAdapterConfig with canonical type reference
sed -i 's/pub struct ExtensibleAdapterConfig/// MIGRATED: ExtensibleAdapterConfig -> CanonicalAdapterConfig/g' "crates/beardog-adapters/src/universal/extensible_adapter.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/service_discovery.rs..."

# Add import: use beardog_types::config::UnifiedDiscoveryConfig;

# Replace DiscoveryConfig with canonical type reference
sed -i 's/pub struct DiscoveryConfig/// MIGRATED: DiscoveryConfig -> UnifiedDiscoveryConfig/g' "crates/beardog-adapters/src/universal/service_discovery.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/security_provider_bridge/mod.rs..."

# Add import: use beardog_types::config::CanonicalAdapterConfig;

# Replace BridgeConfig with canonical type reference
sed -i 's/pub struct BridgeConfig/// MIGRATED: BridgeConfig -> CanonicalAdapterConfig/g' "crates/beardog-adapters/src/universal/security_provider_bridge/mod.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/vendor_adapter/mod.rs..."

# Add import: use beardog_types::config::CanonicalAdapterConfig;

# Replace UniversalAdapterConfig with canonical type reference
sed -i 's/pub struct UniversalAdapterConfig/// MIGRATED: UniversalAdapterConfig -> CanonicalAdapterConfig/g' "crates/beardog-adapters/src/universal/vendor_adapter/mod.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/vendor_adapter/discovery/engine.rs..."

# Add import: use beardog_types::config::UnifiedDiscoveryConfig;
# Add import: use beardog_types::config::UnifiedNetworkConfig;

# Replace DiscoveryEngineConfig with canonical type reference
sed -i 's/pub struct DiscoveryEngineConfig/// MIGRATED: DiscoveryEngineConfig -> UnifiedDiscoveryConfig/g' "crates/beardog-adapters/src/universal/vendor_adapter/discovery/engine.rs"
# Replace TlsConfig with canonical type reference
sed -i 's/pub struct TlsConfig/// MIGRATED: TlsConfig -> UnifiedNetworkConfig/g' "crates/beardog-adapters/src/universal/vendor_adapter/discovery/engine.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/vendor_adapter/routing/performance.rs..."

# Add import: use beardog_types::config::UnifiedPerformanceConfig;

# Replace PerformanceRoutingConfig with canonical type reference
sed -i 's/pub struct PerformanceRoutingConfig/// MIGRATED: PerformanceRoutingConfig -> UnifiedPerformanceConfig/g' "crates/beardog-adapters/src/universal/vendor_adapter/routing/performance.rs"

echo "Migrating configurations in crates/beardog-adapters/src/universal/vendor_adapter/core/capability_handler.rs..."

# Add import: use beardog_types::config::UnifiedSecurityConfig;

# Replace OAuth2Config with canonical type reference
sed -i 's/pub struct OAuth2Config/// MIGRATED: OAuth2Config -> UnifiedSecurityConfig/g' "crates/beardog-adapters/src/universal/vendor_adapter/core/capability_handler.rs"

echo "Configuration migration completed for beardog-adapters"
echo "Please review changes and update imports manually"
echo "Run 'cargo check' to verify compilation"