#!/bin/bash

# BearDog Configuration Migration Script
# Converts legacy TOML configuration files to unified environment variables

set -e

VERSION="3.0.0"
SCRIPT_NAME="BearDog Config Migration"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print banner
print_banner() {
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                 BearDog Configuration Migration              ║"
    echo "║                      Version ${VERSION}                           ║"
    echo "║                                                              ║"
    echo "║  Converts legacy TOML configs to unified environment vars   ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Print usage
print_usage() {
    echo -e "${YELLOW}Usage:${NC}"
    echo "  $0 <legacy-config.toml> [output-env-file]"
    echo ""
    echo -e "${YELLOW}Examples:${NC}"
    echo "  $0 configs/production-config.toml"
    echo "  $0 configs/development-config.toml my-dev.env"
    echo ""
    echo -e "${YELLOW}Options:${NC}"
    echo "  -h, --help    Show this help message"
    echo "  -v, --version Show version information"
}

# Parse TOML and extract values (simplified parser)
parse_toml_value() {
    local file="$1"
    local key="$2"
    local section="$3"
    
    if [ -n "$section" ]; then
        # Look for value in specific section
        awk -v section="[$section]" -v key="$key" '
        BEGIN { in_section = 0 }
        $0 == section { in_section = 1; next }
        /^\[/ && in_section { in_section = 0 }
        in_section && $0 ~ "^" key " *=" {
            gsub(/^[^=]*= */, "")
            gsub(/^"/, "")
            gsub(/"$/, "")
            print $0
            exit
        }' "$file"
    else
        # Look for value anywhere
        grep "^$key *=" "$file" | head -1 | sed 's/^[^=]*= *//' | sed 's/^"//' | sed 's/"$//'
    fi
}

# Generate environment variables from TOML
generate_env_vars() {
    local input_file="$1"
    local output_file="$2"
    
    echo -e "${BLUE}🔄 Analyzing configuration file: ${input_file}${NC}"
    
    if [ ! -f "$input_file" ]; then
        echo -e "${RED}❌ Error: Configuration file not found: ${input_file}${NC}"
        exit 1
    fi
    
    # Create output file
    cat > "$output_file" << 'EOF'
# BearDog Environment Configuration
# Generated by migration script from legacy TOML configuration
# Source this file: source <filename>

EOF
    
    echo -e "${GREEN}📝 Generating environment variables...${NC}"
    
    # Application settings
    echo "# Application Settings" >> "$output_file"
    
    local app_name=$(parse_toml_value "$input_file" "name" "app")
    if [ -n "$app_name" ]; then
        echo "export BEARDOG_APP_NAME=\"$app_name\"" >> "$output_file"
    fi
    
    local environment=$(parse_toml_value "$input_file" "environment" "app")
    if [ -n "$environment" ]; then
        echo "export BEARDOG_ENVIRONMENT=\"$environment\"" >> "$output_file"
    fi
    
    local debug=$(parse_toml_value "$input_file" "debug" "app")
    if [ -n "$debug" ]; then
        echo "export BEARDOG_DEBUG=\"$debug\"" >> "$output_file"
    fi
    
    local standalone=$(parse_toml_value "$input_file" "standalone_mode" "app")
    if [ -n "$standalone" ]; then
        echo "export BEARDOG_STANDALONE_MODE=\"$standalone\"" >> "$output_file"
    fi
    
    echo "" >> "$output_file"
    
    # Network settings
    echo "# Network Settings" >> "$output_file"
    
    local http_enabled=$(parse_toml_value "$input_file" "enabled" "network.http")
    if [ -n "$http_enabled" ]; then
        echo "export BEARDOG_HTTP_ENABLED=\"$http_enabled\"" >> "$output_file"
    fi
    
    local http_bind=$(parse_toml_value "$input_file" "bind_address" "network.http")
    if [ -n "$http_bind" ]; then
        echo "export BEARDOG_HTTP_BIND=\"$http_bind\"" >> "$output_file"
    fi
    
    local http_port=$(parse_toml_value "$input_file" "port" "network.http")
    if [ -n "$http_port" ]; then
        echo "export BEARDOG_HTTP_PORT=\"$http_port\"" >> "$output_file"
    fi
    
    local https_enabled=$(parse_toml_value "$input_file" "enabled" "network.https")
    if [ -n "$https_enabled" ]; then
        echo "export BEARDOG_HTTPS_ENABLED=\"$https_enabled\"" >> "$output_file"
    fi
    
    local cert_path=$(parse_toml_value "$input_file" "cert_path" "network.https")
    if [ -n "$cert_path" ]; then
        echo "export BEARDOG_CERT_PATH=\"$cert_path\"" >> "$output_file"
    fi
    
    local key_path=$(parse_toml_value "$input_file" "key_path" "network.https")
    if [ -n "$key_path" ]; then
        echo "export BEARDOG_KEY_PATH=\"$key_path\"" >> "$output_file"
    fi
    
    echo "" >> "$output_file"
    
    # Security settings
    echo "# Security Settings" >> "$output_file"
    
    local security_level=$(parse_toml_value "$input_file" "level" "security")
    if [ -n "$security_level" ]; then
        echo "export BEARDOG_SECURITY_LEVEL=\"$security_level\"" >> "$output_file"
    fi
    
    local hsm_enabled=$(parse_toml_value "$input_file" "enable_hsm" "security")
    if [ -n "$hsm_enabled" ]; then
        echo "export BEARDOG_HSM_ENABLED=\"$hsm_enabled\"" >> "$output_file"
    fi
    
    local token_expiration=$(parse_toml_value "$input_file" "token_expiration_seconds" "security")
    if [ -n "$token_expiration" ]; then
        echo "export BEARDOG_TOKEN_EXPIRATION=\"$token_expiration\"" >> "$output_file"
    fi
    
    local max_failed=$(parse_toml_value "$input_file" "max_failed_logins" "security")
    if [ -n "$max_failed" ]; then
        echo "export BEARDOG_MAX_FAILED_LOGINS=\"$max_failed\"" >> "$output_file"
    fi
    
    local mfa_required=$(parse_toml_value "$input_file" "required" "security.mfa")
    if [ -n "$mfa_required" ]; then
        echo "export BEARDOG_MFA_REQUIRED=\"$mfa_required\"" >> "$output_file"
    fi
    
    echo "" >> "$output_file"
    
    # Performance settings
    echo "# Performance Settings" >> "$output_file"
    
    local request_timeout=$(parse_toml_value "$input_file" "request_timeout" "network.timeout")
    if [ -n "$request_timeout" ]; then
        echo "export BEARDOG_REQUEST_TIMEOUT=\"$request_timeout\"" >> "$output_file"
    fi
    
    local worker_threads=$(parse_toml_value "$input_file" "worker_threads" "performance")
    if [ -n "$worker_threads" ]; then
        echo "export BEARDOG_WORKER_THREADS=\"$worker_threads\"" >> "$output_file"
    fi
    
    echo "" >> "$output_file"
    
    # Add reminder about secrets
    cat >> "$output_file" << 'EOF'
# IMPORTANT: Set these secrets manually for security
# export BEARDOG_HSM_PIN="<your-secure-hsm-pin>"
# export BEARDOG_SMTP_SERVER="<your-smtp-server>"

# Additional environment-specific variables may be needed
# Refer to configs/environments/ for complete examples
EOF
    
    echo -e "${GREEN}✅ Migration complete!${NC}"
    echo -e "${BLUE}📄 Generated environment file: ${output_file}${NC}"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "1. Review the generated environment file"
    echo "2. Set any missing secrets (HSM PIN, SMTP server, etc.)"
    echo "3. Test with: source ${output_file}"
    echo "4. Use unified config: export BEARDOG_CONFIG=configs/beardog-config-template.toml"
}

# Validate migration
validate_migration() {
    local env_file="$1"
    
    echo -e "${BLUE}🔍 Validating migration...${NC}"
    
    if [ ! -f "$env_file" ]; then
        echo -e "${RED}❌ Environment file not found: ${env_file}${NC}"
        return 1
    fi
    
    # Count environment variables
    local var_count=$(grep -c "^export BEARDOG_" "$env_file" || true)
    
    echo -e "${GREEN}✅ Found ${var_count} BearDog environment variables${NC}"
    
    # Check for common required variables
    local required_vars=("BEARDOG_ENVIRONMENT" "BEARDOG_HTTP_ENABLED")
    local missing_vars=()
    
    for var in "${required_vars[@]}"; do
        if ! grep -q "^export ${var}=" "$env_file"; then
            missing_vars+=("$var")
        fi
    done
    
    if [ ${#missing_vars[@]} -gt 0 ]; then
        echo -e "${YELLOW}⚠️  Warning: Some common variables may be missing:${NC}"
        for var in "${missing_vars[@]}"; do
            echo "   - $var"
        done
        echo "   Consider adding them manually if needed."
    fi
    
    return 0
}

# Main function
main() {
    print_banner
    
    # Parse arguments
    case "${1:-}" in
        -h|--help)
            print_usage
            exit 0
            ;;
        -v|--version)
            echo "$SCRIPT_NAME version $VERSION"
            exit 0
            ;;
        "")
            echo -e "${RED}❌ Error: No configuration file specified${NC}"
            print_usage
            exit 1
            ;;
    esac
    
    local input_file="$1"
    local output_file="${2:-beardog-migrated.env}"
    
    # Perform migration
    generate_env_vars "$input_file" "$output_file"
    
    # Validate results
    validate_migration "$output_file"
    
    echo ""
    echo -e "${GREEN}🎉 Configuration migration completed successfully!${NC}"
    echo -e "${BLUE}Use the new unified configuration system with:${NC}"
    echo "   source ${output_file}"
    echo "   export BEARDOG_CONFIG=configs/beardog-config-template.toml"
}

# Run main function with all arguments
main "$@" 