#!/bin/bash
# Migration script for beardog-tunnel configuration consolidation
# Generated by BearDog Configuration Consolidation Migrator

set -e

CRATE_DIR="crates/beardog-tunnel"

echo "Starting configuration migration for beardog-tunnel..."

echo "Migrating configurations in crates/beardog-tunnel/src/universal_hsm/providers/software/config.rs..."

# Add import: use beardog_types::config::UnifiedSecurityConfig;

# Replace SecurityLevelConfig with canonical type reference
sed -i 's/pub struct SecurityLevelConfig/// MIGRATED: SecurityLevelConfig -> UnifiedSecurityConfig/g' "crates/beardog-tunnel/src/universal_hsm/providers/software/config.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/universal_hsm_discovery/mod.rs..."

# Add import: use beardog_types::config::UnifiedDiscoveryConfig;

# Replace DiscoveryConfig with canonical type reference
sed -i 's/pub struct DiscoveryConfig/// MIGRATED: DiscoveryConfig -> UnifiedDiscoveryConfig/g' "crates/beardog-tunnel/src/universal_hsm_discovery/mod.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/universal_hsm_discovery/universal_adapter/external_primal_client.rs..."

# Add import: use beardog_types::config::UnifiedMonitoringConfig;

# Replace HealthCheckConfig with canonical type reference
sed -i 's/pub struct HealthCheckConfig/// MIGRATED: HealthCheckConfig -> UnifiedMonitoringConfig/g' "crates/beardog-tunnel/src/universal_hsm_discovery/universal_adapter/external_primal_client.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/universal_hsm_discovery/universal_adapter/service_discovery.rs..."

# Add import: use beardog_types::config::UnifiedDiscoveryConfig;

# Replace DiscoveryConfig with canonical type reference
sed -i 's/pub struct DiscoveryConfig/// MIGRATED: DiscoveryConfig -> UnifiedDiscoveryConfig/g' "crates/beardog-tunnel/src/universal_hsm_discovery/universal_adapter/service_discovery.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/universal_hsm_discovery/universal_adapter/operation_routing.rs..."

# Add import: use beardog_types::config::UnifiedMonitoringConfig;

# Replace HealthCheckConfig with canonical type reference
sed -i 's/pub struct HealthCheckConfig/// MIGRATED: HealthCheckConfig -> UnifiedMonitoringConfig/g' "crates/beardog-tunnel/src/universal_hsm_discovery/universal_adapter/operation_routing.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/config.rs..."

# Add import: use beardog_types::config::UnifiedPerformanceConfig;
# Add import: use beardog_types::config::UnifiedMonitoringConfig;

# Replace PerformanceConfig with canonical type reference
sed -i 's/pub struct PerformanceConfig/// MIGRATED: PerformanceConfig -> UnifiedPerformanceConfig/g' "crates/beardog-tunnel/src/tunnel/config.rs"
# Replace MonitoringConfig with canonical type reference
sed -i 's/pub struct MonitoringConfig/// MIGRATED: MonitoringConfig -> UnifiedMonitoringConfig/g' "crates/beardog-tunnel/src/tunnel/config.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/config.rs..."

# Add import: use beardog_types::config::UnifiedPerformanceConfig;

# Replace PerformanceConfig with canonical type reference
sed -i 's/pub struct PerformanceConfig/// MIGRATED: PerformanceConfig -> UnifiedPerformanceConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/config.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/software_hsm/mod.rs..."

# Add import: use beardog_types::config::UnifiedPerformanceConfig;
# Add import: use beardog_types::config::UnifiedDatabaseConfig;

# Replace DatabaseConfig with canonical type reference
sed -i 's/pub struct DatabaseConfig/// MIGRATED: DatabaseConfig -> UnifiedDatabaseConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/software_hsm/mod.rs"
# Replace PerformanceConfig with canonical type reference
sed -i 's/pub struct PerformanceConfig/// MIGRATED: PerformanceConfig -> UnifiedPerformanceConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/software_hsm/mod.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/manager/config.rs..."

# Add import: use beardog_types::config::UnifiedPerformanceConfig;

# Replace PerformanceConfig with canonical type reference
sed -i 's/pub struct PerformanceConfig/// MIGRATED: PerformanceConfig -> UnifiedPerformanceConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/manager/config.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/universal_discovery/mod.rs..."

# Add import: use beardog_types::config::UnifiedDiscoveryConfig;

# Replace DiscoveryConfig with canonical type reference
sed -i 's/pub struct DiscoveryConfig/// MIGRATED: DiscoveryConfig -> UnifiedDiscoveryConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/universal_discovery/mod.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/universal_discovery/discovery_engine.rs..."

# Add import: use beardog_types::config::UnifiedNetworkConfig;

# Replace NetworkScanConfig with canonical type reference
sed -i 's/pub struct NetworkScanConfig/// MIGRATED: NetworkScanConfig -> UnifiedNetworkConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/universal_discovery/discovery_engine.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/types/config.rs..."

# Add import: use beardog_types::config::UnifiedPerformanceConfig;
# Add import: use beardog_types::config::UnifiedSecurityConfig;
# Add import: use beardog_types::config::UnifiedDatabaseConfig;
# Add import: use beardog_types::config::UnifiedMonitoringConfig;

# Replace SecurityConfig with canonical type reference
sed -i 's/pub struct SecurityConfig/// MIGRATED: SecurityConfig -> UnifiedSecurityConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/config.rs"
# Replace PerformanceConfig with canonical type reference
sed -i 's/pub struct PerformanceConfig/// MIGRATED: PerformanceConfig -> UnifiedPerformanceConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/config.rs"
# Replace MonitoringConfig with canonical type reference
sed -i 's/pub struct MonitoringConfig/// MIGRATED: MonitoringConfig -> UnifiedMonitoringConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/config.rs"
# Replace AuthConfig with canonical type reference
sed -i 's/pub struct AuthConfig/// MIGRATED: AuthConfig -> UnifiedSecurityConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/config.rs"
# Replace HealthCheckConfig with canonical type reference
sed -i 's/pub struct HealthCheckConfig/// MIGRATED: HealthCheckConfig -> UnifiedMonitoringConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/config.rs"
# Replace DatabaseConfig with canonical type reference
sed -i 's/pub struct DatabaseConfig/// MIGRATED: DatabaseConfig -> UnifiedDatabaseConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/config.rs"

echo "Migrating configurations in crates/beardog-tunnel/src/tunnel/hsm/types/canonical.rs..."

# Add import: use beardog_types::config::UnifiedDiscoveryConfig;

# Replace DiscoveryConfig with canonical type reference
sed -i 's/pub struct DiscoveryConfig/// MIGRATED: DiscoveryConfig -> UnifiedDiscoveryConfig/g' "crates/beardog-tunnel/src/tunnel/hsm/types/canonical.rs"

echo "Configuration migration completed for beardog-tunnel"
echo "Please review changes and update imports manually"
echo "Run 'cargo check' to verify compilation"