// SPDX-License-Identifier: AGPL-3.0-or-later

//! Wire types and service trait for tarpc binary RPC.
//!
//! This module defines the `BearDogRpc` service trait (30 methods) and all
//! associated request/response types. The trait is code-generated by the
//! `#[tarpc::service]` macro — both the server-side trait and the
//! `BearDogRpcClient` stub are emitted here.

/// Health status returned by the tarpc health check.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TarpcHealthStatus {
    /// Whether the service is healthy.
    pub healthy: bool,
    /// Primal name.
    pub primal: String,
    /// Crate version.
    pub version: String,
    /// Number of tarpc methods served.
    pub tarpc_method_count: u32,
    /// Number of JSON-RPC methods served.
    pub jsonrpc_method_count: u32,
}

/// Result of an Ed25519 signing operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SignResult {
    /// Raw 64-byte Ed25519 signature.
    pub signature: Vec<u8>,
    /// 32-byte public key corresponding to the signing key.
    pub public_key: Vec<u8>,
}

/// Result of an AEAD encryption operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AeadCiphertext {
    /// Encrypted data (without tag).
    pub ciphertext: Vec<u8>,
    /// 96-bit nonce used for encryption.
    pub nonce: Vec<u8>,
    /// 128-bit authentication tag.
    pub tag: Vec<u8>,
}

/// X25519 ephemeral keypair.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct X25519Keypair {
    /// 32-byte secret key.
    pub secret_key: Vec<u8>,
    /// 32-byte public key.
    pub public_key: Vec<u8>,
}

/// Ionic token issuance result.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct IonicTokenResult {
    /// Compact ionic token string (header.payload.signature).
    pub token: String,
    /// DID of the issuing primal.
    pub issuer: String,
    /// Subject the token was issued for.
    pub subject: String,
    /// Scope patterns the token covers.
    pub scope: Vec<String>,
    /// Token lifetime in seconds.
    pub ttl_secs: i64,
}

/// Ionic token verification result.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct IonicVerifyResult {
    /// Whether the token is valid.
    pub valid: bool,
    /// Issuer DID from the token claims.
    pub issuer: Option<String>,
    /// Subject from the token claims.
    pub subject: Option<String>,
    /// Scope patterns from the token claims.
    pub scope: Vec<String>,
    /// Expiry timestamp (Unix seconds).
    pub exp: Option<i64>,
    /// Error description if invalid.
    pub error: Option<String>,
}

/// Public key info for the primal's identity.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PublicKeyInfo {
    /// Base64-encoded Ed25519 public key.
    pub public_key_b64: String,
    /// Hex-encoded Ed25519 public key.
    pub public_key_hex: String,
    /// DID (`did:key:z6Mk...`) for the primal.
    pub did: String,
}

/// Total number of tarpc RPC methods served.
pub const TARPC_METHOD_COUNT: u32 = 30;

#[expect(
    missing_docs,
    reason = "tarpc::service macro generates the trait and helper types; docs on individual methods below"
)]
#[tarpc::service]
pub trait BearDogRpc {
    // ── Health ──────────────────────────────────────────────────────────

    /// Health check — returns primal status without JSON overhead.
    async fn health_check() -> TarpcHealthStatus;

    /// Crate version string.
    async fn version() -> String;

    // ── Hash ───────────────────────────────────────────────────────────

    /// BLAKE3 hash — provenance hot-path (CAS, data braids).
    async fn blake3_hash(data: Vec<u8>) -> Vec<u8>;

    /// SHA-256 hash.
    async fn sha256(data: Vec<u8>) -> Vec<u8>;

    /// SHA-384 hash.
    async fn sha384(data: Vec<u8>) -> Vec<u8>;

    /// SHA-512 hash.
    async fn sha512(data: Vec<u8>) -> Vec<u8>;

    // ── MAC ────────────────────────────────────────────────────────────

    /// HMAC-SHA256.
    async fn hmac_sha256(key: Vec<u8>, data: Vec<u8>) -> Result<Vec<u8>, String>;

    /// BLAKE3 keyed hash (MAC).
    async fn blake3_keyed(key: Vec<u8>, data: Vec<u8>) -> Result<Vec<u8>, String>;

    // ── KDF ────────────────────────────────────────────────────────────

    /// HKDF-SHA256 key derivation.
    async fn hkdf_sha256(
        ikm: Vec<u8>,
        salt: Vec<u8>,
        info: Vec<u8>,
        output_length: u32,
    ) -> Result<Vec<u8>, String>;

    /// BLAKE3 key derivation.
    async fn blake3_derive_key(context: String, key_material: Vec<u8>) -> Vec<u8>;

    /// Argon2id password hashing (memory-hard).
    async fn argon2id_hash(password: Vec<u8>, salt: Vec<u8>) -> Result<Vec<u8>, String>;

    // ── Signing ────────────────────────────────────────────────────────

    /// Ed25519 sign — derived key from KDF(FAMILY_SEED, key_id, "signing").
    async fn sign_ed25519(key_id: String, message: Vec<u8>) -> Result<SignResult, String>;

    /// Ed25519 verify.
    async fn verify_ed25519(
        public_key: Vec<u8>,
        message: Vec<u8>,
        signature: Vec<u8>,
    ) -> Result<bool, String>;

    // ── Key Exchange ───────────────────────────────────────────────────

    /// X25519 generate ephemeral keypair.
    async fn x25519_generate_ephemeral() -> X25519Keypair;

    /// X25519 derive shared secret.
    async fn x25519_derive_secret(
        secret_key: Vec<u8>,
        peer_public_key: Vec<u8>,
    ) -> Result<Vec<u8>, String>;

    // ── AEAD ───────────────────────────────────────────────────────────

    /// ChaCha20-Poly1305 encrypt (constant-time, no AES-NI required).
    async fn chacha20_poly1305_encrypt(
        data: Vec<u8>,
        key: Vec<u8>,
        aad: Vec<u8>,
    ) -> Result<AeadCiphertext, String>;

    /// ChaCha20-Poly1305 decrypt.
    async fn chacha20_poly1305_decrypt(
        ciphertext: Vec<u8>,
        nonce: Vec<u8>,
        tag: Vec<u8>,
        key: Vec<u8>,
        aad: Vec<u8>,
    ) -> Result<Vec<u8>, String>;

    /// AES-256-GCM encrypt.
    async fn aes256_gcm_encrypt(
        data: Vec<u8>,
        key: Vec<u8>,
        aad: Vec<u8>,
    ) -> Result<AeadCiphertext, String>;

    /// AES-256-GCM decrypt.
    async fn aes256_gcm_decrypt(
        ciphertext: Vec<u8>,
        nonce: Vec<u8>,
        tag: Vec<u8>,
        key: Vec<u8>,
        aad: Vec<u8>,
    ) -> Result<Vec<u8>, String>;

    /// AES-128-GCM encrypt.
    async fn aes128_gcm_encrypt(
        data: Vec<u8>,
        key: Vec<u8>,
        aad: Vec<u8>,
    ) -> Result<AeadCiphertext, String>;

    /// AES-128-GCM decrypt.
    async fn aes128_gcm_decrypt(
        ciphertext: Vec<u8>,
        nonce: Vec<u8>,
        tag: Vec<u8>,
        key: Vec<u8>,
        aad: Vec<u8>,
    ) -> Result<Vec<u8>, String>;

    // ── Auth / Ionic Token ─────────────────────────────────────────────

    /// Issue an ionic capability token.
    async fn auth_issue_ionic(
        subject: String,
        scope: Vec<String>,
        ttl_secs: i64,
    ) -> IonicTokenResult;

    /// Verify an ionic token string, returning claims or error.
    async fn auth_verify_ionic(token: String) -> IonicVerifyResult;

    /// Get the primal's Ed25519 public key and DID.
    async fn auth_public_key() -> PublicKeyInfo;

    /// Issue a session token (simplified — auto-scoped by purpose).
    async fn auth_issue_session(
        purpose: String,
        user: String,
    ) -> IonicTokenResult;

    /// Generate an ephemeral Ed25519 identity keypair.
    async fn identity_create() -> SignResult;

    /// Derive a key from FAMILY_SEED via BLAKE3 KDF.
    async fn derive_key(key_id: String, purpose: String) -> Result<Vec<u8>, String>;
}
