[package]
name = "beardog-utils"
version.workspace = true
edition = "2024"
description = "Utility functions for BearDog Security Manager"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ecoPrimals/beardog"
rust-version = "1.93.0"
authors = [ "BearDog Team <team@beardog.dev>",]
homepage = "https://beardog.dev"
documentation = "https://docs.rs/beardog"
keywords = [ "utilities", "helpers", "beardog", "ecosystem", "tools",]
categories = [ "development-tools", "data-structures", "algorithms",]

[lints]
workspace = true

[dependencies]
beardog-errors = { workspace = true }
beardog-types = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "sync", "time"] }
tracing = { workspace = true }
zeroize = { workspace = true }

[features]
test-utils = []
